### ISSUE TITLE
Observable which fires few values at once

### ISSUE THREAD

**Issue by zoryamba** [parzh/observable-to-async-generator#8]
Hi. Found your lib useful while working with NestJS. I had to take data from microservice (which is received as an observable) and pass it as readable stream to front-end (kinda Readable.from(otag(observable))).

But i faced some issues when observable emits few values at once. In case I do
```
const observable = from([1,2,3]);
for await (const i of otag(observable)) {
  console.log(i)
}
```
I don't even hit that console.log.

**Comment by zoryamba** [comment]
The reason is both promises and observables work with microtask queue. [(More details)](https://javascript.info/event-loop)

So when we hit that `for await` first time, we already have 4 callbacks in microtasks queue:

<img width="385" alt="Screen Shot 2022-02-20 at 11 19 04 AM" src="https://user-images.githubusercontent.com/21248500/154836279-6122e617-78b2-413c-9add-bcd289afda49.png">

after hitting first await here:
<img width="380" alt="Screen Shot 2022-02-20 at 11 20 18 AM" src="https://user-images.githubusercontent.com/21248500/154836372-5f018d96-dd47-4491-9c41-e826698c9f1b.png">

control goes to event loop and it starting to process callbacks from queue. And after processing first `next` here:
<img width="366" alt="Screen Shot 2022-02-20 at 11 22 43 AM" src="https://user-images.githubusercontent.com/21248500/154836410-b3cb21c2-5af4-4223-9f0d-2768d7aefe4b.png">

await gets done and all the code, going after await, passed to the same microtask queue:
<img width="504" alt="Screen Shot 2022-02-20 at 11 29 17 AM" src="https://user-images.githubusercontent.com/21248500/154836460-3cc5dcc4-20c6-4264-99f2-fd267ddf6352.png">

So when we hit `if (finished)` for the first time, all values are already processed and we get no values emited from generator. 
Try this test, it will fail with empty result array:

```
it.only("should allow iterating over items in observable, using `for await .. of` construct", async () => {
	const arr = [42,42,42];
	let observable = from(arr);

	const values = [];

	for await (const value of otag(observable)) {
		expect(value).toBe(42);
		values.push(value);
	}

	expect(values).toStrictEqual(arr);
});
```

**Comment by parzhitsky** [comment]
Sure, I'll take a look. Thanks for the issue!

**Comment by zoryamba** [comment]
So simple solution here is to wrap all the handlers with setTimeout to move `next`, `error` and `complete` handlers to macrotask queue and so to give while(true) loop more priority

So that  at first `await`:
<img width="380" alt="Screen Shot 2022-02-20 at 11 20 18 AM" src="https://user-images.githubusercontent.com/21248500/154836822-9e129348-0b45-4634-8f15-ab8e9ece45e8.png">
 
we move all these handlers to macrotask queue with lower priority

<img width="385" alt="Screen Shot 2022-02-20 at 11 19 04 AM" src="https://user-images.githubusercontent.com/21248500/154836851-c11086f9-6742-4cf9-9932-1c2c45c1238b.png">

 and microtask queue becomes empty.

First `next` handler gets processed and at this point:
<img width="366" alt="Screen Shot 2022-02-20 at 11 22 43 AM" src="https://user-images.githubusercontent.com/21248500/154836873-d6fd1467-c2bb-415a-8377-2a2b2d019989.png">

code after `await` comes to microtasks queue:
<img width="390" alt="Screen Shot 2022-02-20 at 11 43 09 AM" src="https://user-images.githubusercontent.com/21248500/154836961-3356320d-6196-4906-b721-28065342d775.png">

and gets processed before all other handlers

**Comment by zoryamba** [comment]
Here is PR to fix the issue. Any feedback appreciated.

**Comment by zoryamba** [comment]
UPD: updated tests in PR to test both cases: when values fired on timeout and at once

**Comment by zoryamba** [comment]
Could you update the npm package pls? 
Thanks

**Comment by parzhitsky** [comment]
Looks like the GitHub Actions workflow has been canceled due to timeout. Apologies! This happens sometimes with `macos-latest` runners.
